#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg2

runcmd:
  - modprobe br_netfilter
  - sysctl -w net.bridge.bridge-nf-call-iptables=1
  - sysctl -w net.ipv4.ip_forward=1
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - add-apt-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main"
  - apt update
  - apt install -y kubelet=${K8S_VERSION}-00 kubeadm=${K8S_VERSION}-00 kubectl=${K8S_VERSION}-00
  - kubeadm init --pod-network-cidr=${POD_CIDR} --kubernetes-version=${K8S_VERSION}
  - mkdir -p /home/ubuntu/.kube
  - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  - su - ubuntu -c "kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.13.2/install/kubernetes/quick-install.yaml"
